services:
  - type: web
    name: sp13-image-filters
    runtime: python
    repo: https://github.com/YOUR_USERNAME/YOUR_REPO_NAME
    plan: free
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0